### PR TITLE
Added feature #41 and #71

### PR DESCRIPTION
**Pull request by ashishsaranshakya**
- Added #41: The feature includes the option to change notification timing to given option. And I have given discrete values this time around i.e. 5,10,20,30,45 minutes. Could be changes with few minor changes.

- Added #71: The feature include the option to put your phone on either vibrate or silent. It requires user giving permission to change Do Not Disturb mode. It is initially turned off.

### CODE REVIEW

**Comment by ashishsaranshakya** [comment]
The request includes a feature which will turn on the do not disturb mode during class and turn it off after class so that people's phones do not ring between classes. and if they have turned it to vibrate mode then it will vibrate instead of ringing.

**Comment by therealsujitk** [comment]
@ashishsaranshakya sorry for the delay, I'll review this as soon as I get some free time. The DND addition is definitely a good feature, I'll try and merge it for the next release.

**Comment by ashishsaranshakya** [comment]
it has been some time now, when are you going to review the pull request

**Comment by therealsujitk** [comment]
I don't believe it's worth implementing #41 so I've closed it, since this PR attempts to resolve multiple issues I can't review it easily. If you're able to, you can create another PR for #71 alone. In future kindly refrain from opening PRs that resolve multiple issues (unless the root cause is the same) not just here but in any repository.

**Pull request closed without merging**
